project_id = "dnflkxdyfmuubgjnfshe"

[functions.tracking-public]
verify_jwt = false

[functions.register-driver]
verify_jwt = true

[functions.geocoding]
verify_jwt = false

[functions.optimize-route]
verify_jwt = false